import type { AtlasSnapshot } from './types'

export const atlasSnapshot: AtlasSnapshot = {
  business: {
    name: 'Sharma General Store',
    owner: 'Rajesh Sharma',
    location: 'Kanpur, UP',
    category: 'General Store',
    phone: '9876543210',
    gstNumber: '09ABCDE1234F1Z5',
    memberSince: '2024-06-15',
  },

  sales: {
    today: 12400,
    yesterday: 10500,
    thisWeek: 67200,
    lastWeek: 58900,
    thisMonth: 245000,
    lastMonth: 218000,
    todayTransactions: 19,
    trend: [
      { date: '2026-03-01', amount: 9200, transactions: 12 },
      { date: '2026-03-02', amount: 11400, transactions: 18 },
      { date: '2026-03-03', amount: 8700, transactions: 11 },
      { date: '2026-03-04', amount: 13200, transactions: 21 },
      { date: '2026-03-05', amount: 10100, transactions: 15 },
      { date: '2026-03-06', amount: 10500, transactions: 16 },
      { date: '2026-03-07', amount: 12400, transactions: 19 },
    ],
  },

  inventory: {
    totalItems: 142,
    totalValue: 487500,
    lowStockItems: [
      {
        id: '1',
        name: 'Basmati Rice 5kg',
        category: 'Grains',
        price: 500,
        stock: 5,
        unit: 'bags',
        soldThisMonth: 84,
        revenue: 42000,
        daysLeft: 3,
        trend: 'up',
      },
      {
        id: '2',
        name: 'Tata Salt 1kg',
        category: 'Essentials',
        price: 100,
        stock: 12,
        unit: 'packets',
        soldThisMonth: 210,
        revenue: 21000,
        daysLeft: 6,
        trend: 'stable',
      },
    ],
    topProducts: [
      {
        id: '1',
        name: 'Basmati Rice 5kg',
        category: 'Grains',
        price: 500,
        stock: 5,
        unit: 'bags',
        soldThisMonth: 84,
        revenue: 42000,
        daysLeft: 3,
        trend: 'up',
      },
      {
        id: '2',
        name: 'Tata Salt 1kg',
        category: 'Essentials',
        price: 100,
        stock: 32,
        unit: 'packets',
        soldThisMonth: 210,
        revenue: 21000,
        trend: 'stable',
      },
      {
        id: '3',
        name: 'Surf Excel 1kg',
        category: 'Household',
        price: 300,
        stock: 28,
        unit: 'packets',
        soldThisMonth: 60,
        revenue: 18000,
        trend: 'up',
      },
      {
        id: '4',
        name: 'Fortune Sunflower Oil 1L',
        category: 'Oils',
        price: 300,
        stock: 40,
        unit: 'bottles',
        soldThisMonth: 45,
        revenue: 13500,
        trend: 'stable',
      },
      {
        id: '5',
        name: 'Amul Butter 500g',
        category: 'Dairy',
        price: 250,
        stock: 15,
        unit: 'packs',
        soldThisMonth: 38,
        revenue: 9500,
        trend: 'up',
      },
    ],
    slowMoving: [
      {
        id: '6',
        name: 'Bournvita 500g',
        category: 'Beverages',
        price: 320,
        stock: 24,
        unit: 'jars',
        soldThisMonth: 3,
        revenue: 960,
        trend: 'down',
      },
      {
        id: '7',
        name: 'Nescafe Classic 100g',
        category: 'Beverages',
        price: 280,
        stock: 18,
        unit: 'jars',
        soldThisMonth: 2,
        revenue: 560,
        trend: 'down',
      },
    ],
  },

  customers: {
    total: 847,
    active: 312,
    inactive: 535,
    newThisMonth: 23,
    topCustomers: [
      {
        id: '1',
        name: 'Priya Verma',
        phone: '9812345678',
        totalSpent: 18400,
        visits: 24,
        lastVisit: '2026-03-07',
        tags: ['loyal', 'bulk-buyer'],
      },
      {
        id: '2',
        name: 'Amit Singh',
        phone: '9823456789',
        totalSpent: 14200,
        visits: 18,
        lastVisit: '2026-03-06',
        tags: ['regular'],
      },
      {
        id: '3',
        name: 'Sunita Devi',
        phone: '9834567890',
        totalSpent: 12800,
        visits: 16,
        lastVisit: '2026-03-05',
        tags: ['regular', 'dairy-lover'],
      },
    ],
    recentActivity: [
      {
        customerId: '1',
        name: 'Priya Verma',
        action: 'Purchase',
        amount: 1240,
        items: ['Basmati Rice 5kg', 'Amul Butter 500g'],
        time: '2 hours ago',
      },
      {
        customerId: '4',
        name: 'Rakesh Kumar',
        action: 'Purchase',
        amount: 580,
        items: ['Tata Salt 1kg', 'Surf Excel 1kg'],
        time: '4 hours ago',
      },
      {
        customerId: '2',
        name: 'Amit Singh',
        action: 'Purchase',
        amount: 2100,
        items: ['Fortune Sunflower Oil 1L', 'Basmati Rice 5kg', 'Tata Salt 1kg'],
        time: 'Yesterday 6 PM',
      },
      {
        customerId: '5',
        name: 'Meena Gupta',
        action: 'New',
        amount: 420,
        items: ['Amul Butter 500g', 'Tata Salt 1kg'],
        time: 'Yesterday 2 PM',
      },
    ],
  },
}
