import type { SparkData } from './types'

export const sparkSnapshot: SparkData = {
  campaigns: {
    total: 8,
    running: 2,
    list: [
      {
        id: 'c1',
        name: 'Holi Special Offer',
        status: 'running',
        type: 'whatsapp',
        sentAt: '2026-03-05',
        delivered: 480,
        opened: 312,
        clicked: 89,
        audience: 500,
      },
      {
        id: 'c2',
        name: 'Weekend Grocery Deal',
        status: 'running',
        type: 'whatsapp',
        sentAt: '2026-03-07',
        delivered: 210,
        opened: 148,
        clicked: 42,
        audience: 220,
      },
      {
        id: 'c3',
        name: 'Republic Day Sale',
        status: 'completed',
        type: 'whatsapp',
        sentAt: '2026-01-26',
        delivered: 620,
        opened: 410,
        clicked: 134,
        audience: 650,
      },
      {
        id: 'c4',
        name: 'New Year Offer',
        status: 'completed',
        type: 'social',
        sentAt: '2026-01-01',
        delivered: 380,
        opened: 245,
        clicked: 78,
        audience: 400,
      },
      {
        id: 'c5',
        name: 'Diwali Mega Sale',
        status: 'completed',
        type: 'whatsapp',
        sentAt: '2025-10-20',
        delivered: 780,
        opened: 540,
        clicked: 210,
        audience: 800,
      },
      {
        id: 'c6',
        name: 'Rice & Dal Bundle',
        status: 'completed',
        type: 'reel',
        sentAt: '2025-12-15',
        delivered: 290,
        opened: 180,
        clicked: 56,
        audience: 300,
      },
      {
        id: 'c7',
        name: 'Summer Drinks Special',
        status: 'draft',
        type: 'whatsapp',
        audience: 400,
      },
      {
        id: 'c8',
        name: 'Monthly Grocery Pack',
        status: 'draft',
        type: 'social',
        audience: 250,
      },
    ],
  },
  whatsapp: {
    messagesSentThisMonth: 940,
    deliveryRate: 96.2,
    openRate: 68.4,
    creditsRemaining: 560,
  },
  reelScripts: 12,
  scheduledPosts: 5,
}
